apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drupal-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-user/drupal-k8s
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: drupal-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
